'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NetBakery.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property connections() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connections", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;AdvTree&gt;
        '''  &lt;Node Expanded=&quot;true&quot; Name=&quot;mapModels&quot; DragDropEnabled=&quot;false&quot; Text=&quot;Models&quot; ImageIndex=&quot;18&quot; ImageExpandedIndex=&quot;23&quot;&gt;
        '''    &lt;Node Expanded=&quot;true&quot; Name=&quot;mapMapping&quot; DragDropEnabled=&quot;false&quot; Text=&quot;Mapping&quot; ImageIndex=&quot;18&quot; ImageExpandedIndex=&quot;23&quot;&gt;
        '''    &lt;/Node&gt;
        '''    &lt;Node Expanded=&quot;true&quot; Name=&quot;mapStoreCommands&quot; DragDropEnabled=&quot;false&quot; Text=&quot;StoreCommands&quot; ImageIndex=&quot;18&quot; ImageExpandedIndex=&quot;23&quot;&gt;
        '''      &lt;Node Expanded=&quot;true&quot; Name=&quot;mapStoreCommandModels&quot; DragDropEnabled=&quot;false&quot; Text=&quot;Models&quot; ImageIndex [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property defaultOutputExplorer() As String
            Get
                Return ResourceManager.GetString("defaultOutputExplorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;AdvTree&gt;
        '''  &lt;Node Expanded=&quot;true&quot; Name=&quot;mapModels&quot; DragDropEnabled=&quot;false&quot; Text=&quot;Models&quot; ImageIndex=&quot;18&quot; ImageExpandedIndex=&quot;23&quot;&gt;
        '''    &lt;Node Expanded=&quot;true&quot; Name=&quot;mapMapping&quot; DragDropEnabled=&quot;false&quot; Text=&quot;Mapping&quot; ImageIndex=&quot;18&quot; ImageExpandedIndex=&quot;23&quot; /&gt;
        '''    &lt;Node Expanded=&quot;true&quot; Name=&quot;mapStoreCommands&quot; DragDropEnabled=&quot;false&quot; Text=&quot;StoreCommands&quot; ImageIndex=&quot;18&quot; ImageExpandedIndex=&quot;23&quot;&gt;
        '''      &lt;Node Expanded=&quot;true&quot; Name=&quot;mapStoreCommandFunctions&quot; DragDropEnabled=&quot;false&quot; Text=&quot;Functions&quot; ImageIndex=&quot;18&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property net5OutputExplorer() As String
            Get
                Return ResourceManager.GetString("net5OutputExplorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property netbakery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("netbakery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to int float bool string true false null void iterable object abstract and array as break callable case catch class clone const continue declare default die do echo else elseif empty enddeclare endfor endforeach endif endswitch endwhile eval exit extends final finally fn for foreach function global goto if implements include include_once instanceof insteadof interface isset list match namespace new or print private protected public require require_once return static switch throw trait try unset use var while x [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property php_keywords() As String
            Get
                Return ResourceManager.GetString("php_keywords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;AdvTree&gt;
        '''  &lt;Node Expanded=&quot;true&quot; Name=&quot;mapModels&quot; DragDropEnabled=&quot;false&quot; Text=&quot;Table&quot; ImageIndex=&quot;18&quot; ImageExpandedIndex=&quot;23&quot;&gt;&lt;/Node&gt;
        '''    &lt;Node Expanded=&quot;true&quot; Name=&quot;mapMapping&quot; DragDropEnabled=&quot;false&quot; Text=&quot;Entity&quot; ImageIndex=&quot;18&quot; ImageExpandedIndex=&quot;23&quot;&gt;
        '''    &lt;/Node&gt;
        '''&lt;/AdvTree&gt;.
        '''</summary>
        Friend ReadOnly Property phpOutputExplorer() As String
            Get
                Return ResourceManager.GetString("phpOutputExplorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pngwing_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pngwing.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RibbonGeometry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RibbonGeometry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to abs absolute access acos add add_months adddate admin after aggregate all allocate alter and any app_name are array as asc ascii asin assertion at atan atn2 audit authid authorization autonomous_transaction avg before begin benchmark between bfilename bigint bin binary binary_checksum binary_integer bit bit_count bit_and bit_or blob body boolean both breadth bulk by call cascade cascaded case cast catalog ceil ceiling char char_base character charindex chartorowid check checksum checksum_agg chr class clob  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sql_keywords() As String
            Get
                Return ResourceManager.GetString("sql_keywords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://www.cmbsolutions.nl.
        '''</summary>
        Friend ReadOnly Property updateLocationBaseURL() As String
            Get
                Return ResourceManager.GetString("updateLocationBaseURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to netbakery/v2/latest.php.
        '''</summary>
        Friend ReadOnly Property updateLocationResource() As String
            Get
                Return ResourceManager.GetString("updateLocationResource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to addhandler addressof andalso alias and ansi as assembly attribute auto begin boolean byref byte byval call case catch cbool cbyte cchar cdate cdec cdbl char cint class clng cobj compare const continue cshort csng cstr ctype currency date datetime time decimal declare default delegate dim do double each else elseif end enum erase error event exit explicit false finally for friend function get gettype global gosub goto handles if implement implements imports in inherits integer interface is let lib like load  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vb_keywords() As String
            Get
                Return ResourceManager.GetString("vb_keywords", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
