Imports System.Linq
Imports System.Text
Imports System.Collections.Generic
Imports Netbakery.Models
Imports Netbakery.infoSchema
Imports System

'------------------------------------------------------------------------------
'<auto-generated>
'    This code was generated by a tool.
'    Runtime Version: 16.0.0.0
' 
'    Changes to this file may cause incorrect behavior and will be lost if
'    the code is regenerated.
'</auto-generated>
'------------------------------------------------------------------------------
Namespace My.Templates.php
    '''<summary>
    '''Class to produce the template output
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")>  _
    Partial Public Class Map
        Inherits MapBase
        '''<summary>
        '''Create the template output
        '''</summary>
        Public Overridable Function TransformText() As String
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",9)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("declare(strict_types=1);"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",11)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("namespace App\Model\Entity;"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",13)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("use Cake\ORM\Entity;"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",15)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("/**"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",16)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("* " & _t.singleName & "Entity"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",17)
  For each c in _t.columns 
            
            #End ExternalSource
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",18)
      If c.isNullable Then 
            
            #End ExternalSource
            Me.Write("    ")
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",19)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("* @property  " & c.phpType & "|null $" & c.name))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",20)
      Else 
            
            #End ExternalSource
            Me.Write("    ")
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",21)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("* @property " & c.phpType & " $" & c.name))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",22)
      End If 
            
            #End ExternalSource
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",23)
 Next 
            
            #End ExternalSource
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",24)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("*/"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",26)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("class " & _t.singleName & " extends Entity"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",27)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("{"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",28)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    /**"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",29)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    * Fields that can be mass assigned using newEntity() or patchEntity()."))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",30)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    *"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",31)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    * Note that when '*' is set to true, this allows all unspecified fields to"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",32)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    * be mass assigned. For security purposes, it is advised to set '*' to false"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",33)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    * (or remove it), and explicitly make individual fields accessible as needed."))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",34)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    *"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",35)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    * @var array"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",36)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    */"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",37)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    protected $_accessible = ["))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",38)
 For each c in _t.columns 
            
            #End ExternalSource
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",39)
      If not c.autoincrement Then 
            
            #End ExternalSource
            Me.Write("        ")
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",40)
            Me.Write(Me.ToStringHelper.ToStringWithCulture(c.name & "=> true,"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",41)
      End If 
            
            #End ExternalSource
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",42)
 Next 
            
            #End ExternalSource
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",43)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("    ];"))
            
            #End ExternalSource
            Me.Write(""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))
            
            #ExternalSource("E:\My Documents\localRepos\netbakery\NetBakery\Generators\php\Map.tt",44)
            Me.Write(Me.ToStringHelper.ToStringWithCulture("}"))
            
            #End ExternalSource
            Return Me.GenerationEnvironment.ToString
        End Function
    End Class
    #Region "Base class"
    '''<summary>
    '''Base class for this transformation
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")>  _
    Public Class MapBase
        #Region "Fields"
        Private generationEnvironmentField As Global.System.Text.StringBuilder
        Private errorsField As Global.System.CodeDom.Compiler.CompilerErrorCollection
        Private indentLengthsField As Global.System.Collections.Generic.List(Of Integer)
        Private currentIndentField As String = ""
        Private endsWithNewline As Boolean
        Private sessionField As Global.System.Collections.Generic.IDictionary(Of String, Object)
        #End Region
        #Region "Properties"
        '''<summary>
        '''The string builder that generation-time code is using to assemble generated output
        '''</summary>
        Protected Property GenerationEnvironment() As System.Text.StringBuilder
            Get
                If (Me.generationEnvironmentField Is Nothing) Then
                    Me.generationEnvironmentField = New Global.System.Text.StringBuilder()
                End If
                Return Me.generationEnvironmentField
            End Get
            Set
                Me.generationEnvironmentField = value
            End Set
        End Property
        '''<summary>
        '''The error collection for the generation process
        '''</summary>
        Public ReadOnly Property Errors() As System.CodeDom.Compiler.CompilerErrorCollection
            Get
                If (Me.errorsField Is Nothing) Then
                    Me.errorsField = New Global.System.CodeDom.Compiler.CompilerErrorCollection()
                End If
                Return Me.errorsField
            End Get
        End Property
        '''<summary>
        '''A list of the lengths of each indent that was added with PushIndent
        '''</summary>
        Private ReadOnly Property indentLengths() As System.Collections.Generic.List(Of Integer)
            Get
                If (Me.indentLengthsField Is Nothing) Then
                    Me.indentLengthsField = New Global.System.Collections.Generic.List(Of Integer)()
                End If
                Return Me.indentLengthsField
            End Get
        End Property
        '''<summary>
        '''Gets the current indent we use when adding lines to the output
        '''</summary>
        Public ReadOnly Property CurrentIndent() As String
            Get
                Return Me.currentIndentField
            End Get
        End Property
        '''<summary>
        '''Current transformation session
        '''</summary>
        Public Overridable Property Session() As Global.System.Collections.Generic.IDictionary(Of String, Object)
            Get
                Return Me.sessionField
            End Get
            Set
                Me.sessionField = value
            End Set
        End Property
        #End Region
        #Region "Transform-time helpers"
        '''<summary>
        '''Write text directly into the generated output
        '''</summary>
        Public Overloads Sub Write(ByVal textToAppend As String)
            If String.IsNullOrEmpty(textToAppend) Then
                Return
            End If
            'If we're starting off, or if the previous text ended with a newline,
            'we have to append the current indent first.
            If ((Me.GenerationEnvironment.Length = 0)  _
                        OrElse Me.endsWithNewline) Then
                Me.GenerationEnvironment.Append(Me.currentIndentField)
                Me.endsWithNewline = false
            End If
            'Check if the current text ends with a newline
            If textToAppend.EndsWith(Global.System.Environment.NewLine, Global.System.StringComparison.CurrentCulture) Then
                Me.endsWithNewline = true
            End If
            'This is an optimization. If the current indent is "", then we don't have to do any
            'of the more complex stuff further down.
            If (Me.currentIndentField.Length = 0) Then
                Me.GenerationEnvironment.Append(textToAppend)
                Return
            End If
            'Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(Global.System.Environment.NewLine, (Global.System.Environment.NewLine + Me.currentIndentField))
            'If the text ends with a newline, then we should strip off the indent added at the very end
            'because the appropriate indent will be added when the next time Write() is called
            If Me.endsWithNewline Then
                Me.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - Me.currentIndentField.Length))
            Else
                Me.GenerationEnvironment.Append(textToAppend)
            End If
        End Sub
        '''<summary>
        '''Write text directly into the generated output
        '''</summary>
        Public Overloads Sub WriteLine(ByVal textToAppend As String)
            Me.Write(textToAppend)
            Me.GenerationEnvironment.AppendLine
            Me.endsWithNewline = true
        End Sub
        '''<summary>
        '''Write formatted text directly into the generated output
        '''</summary>
        Public Overloads Sub Write(ByVal format As String, <System.ParamArrayAttribute()> ByVal args() As Object)
            Me.Write(String.Format(Global.System.Globalization.CultureInfo.CurrentCulture, format, args))
        End Sub
        '''<summary>
        '''Write formatted text directly into the generated output
        '''</summary>
        Public Overloads Sub WriteLine(ByVal format As String, <System.ParamArrayAttribute()> ByVal args() As Object)
            Me.WriteLine(String.Format(Global.System.Globalization.CultureInfo.CurrentCulture, format, args))
        End Sub
        '''<summary>
        '''Raise an error
        '''</summary>
        Public Sub [Error](ByVal message As String)
            Dim [error] As System.CodeDom.Compiler.CompilerError = New Global.System.CodeDom.Compiler.CompilerError()
            [error].ErrorText = message
            Me.Errors.Add([error])
        End Sub
        '''<summary>
        '''Raise a warning
        '''</summary>
        Public Sub Warning(ByVal message As String)
            Dim [error] As System.CodeDom.Compiler.CompilerError = New Global.System.CodeDom.Compiler.CompilerError()
            [error].ErrorText = message
            [error].IsWarning = true
            Me.Errors.Add([error])
        End Sub
        '''<summary>
        '''Increase the indent
        '''</summary>
        Public Sub PushIndent(ByVal indent As String)
            If (indent = Nothing) Then
                Throw New Global.System.ArgumentNullException("indent")
            End If
            Me.currentIndentField = (Me.currentIndentField + indent)
            Me.indentLengths.Add(indent.Length)
        End Sub
        '''<summary>
        '''Remove the last indent that was added with PushIndent
        '''</summary>
        Public Function PopIndent() As String
            Dim returnValue As String = ""
            If (Me.indentLengths.Count > 0) Then
                Dim indentLength As Integer = Me.indentLengths((Me.indentLengths.Count - 1))
                Me.indentLengths.RemoveAt((Me.indentLengths.Count - 1))
                If (indentLength > 0) Then
                    returnValue = Me.currentIndentField.Substring((Me.currentIndentField.Length - indentLength))
                    Me.currentIndentField = Me.currentIndentField.Remove((Me.currentIndentField.Length - indentLength))
                End If
            End If
            Return returnValue
        End Function
        '''<summary>
        '''Remove any indentation
        '''</summary>
        Public Sub ClearIndent()
            Me.indentLengths.Clear
            Me.currentIndentField = ""
        End Sub
        #End Region
        #Region "ToString Helpers"
        '''<summary>
        '''Utility class to produce culture-oriented representation of an object as a string.
        '''</summary>
        Public Class ToStringInstanceHelper
            Private formatProviderField  As System.IFormatProvider = Global.System.Globalization.CultureInfo.InvariantCulture
            '''<summary>
            '''Gets or sets format provider to be used by ToStringWithCulture method.
            '''</summary>
            Public Property FormatProvider() As System.IFormatProvider
                Get
                    Return Me.formatProviderField 
                End Get
                Set
                    If (Not (value) Is Nothing) Then
                        Me.formatProviderField  = value
                    End If
                End Set
            End Property
            '''<summary>
            '''This is called from the compile/run appdomain to convert objects within an expression block to a string
            '''</summary>
            Public Function ToStringWithCulture(ByVal objectToConvert As Object) As String
                If (objectToConvert Is Nothing) Then
                    Throw New Global.System.ArgumentNullException("objectToConvert")
                End If
                Dim t As System.Type = objectToConvert.GetType
                Dim method As System.Reflection.MethodInfo = t.GetMethod("ToString", New System.Type() {GetType(System.IFormatProvider)})
                If (method Is Nothing) Then
                    Return objectToConvert.ToString
                Else
                    Return CType(method.Invoke(objectToConvert, New Object() {Me.formatProviderField }),String)
                End If
            End Function
        End Class
        Private toStringHelperField As ToStringInstanceHelper = New ToStringInstanceHelper()
        '''<summary>
        '''Helper to produce culture-oriented representation of an object as a string
        '''</summary>
        Public ReadOnly Property ToStringHelper() As ToStringInstanceHelper
            Get
                Return Me.toStringHelperField
            End Get
        End Property
        #End Region
    End Class
    #End Region
End Namespace
