name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      max-parallel: 4
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Nuget restore solution
      working-directory: NetBakery\
      run: nuget restore NetBakery.sln

    - name: MSBuild of solution
      working-directory: NetBakery\
      run: msbuild NetBakery.sln /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /m /verbosity:minimal
