name: Build and Deploy

on:
  pull_request:
    branches:
    - main

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./NetBakery.sln
  INNO_SETUP: D:\a\NetBakery\NetBakery\packages\Tools.InnoSetup.6.4.3\tools\ISCC.exe
  INSTALLER_FILE_PATH: ./NetBakerySetup.iss

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        build_configuration: [Release]
        build_platform: [x64]
        
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.build_configuration}} /p:platform="${{matrix.build_platform}}" ${{env.SOLUTION_FILE_PATH}}

    - name: Create Installer
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ${{env.INNO_SETUP}} ${{env.INSTALLER_FILE_PATH}}

    - name: Archive artifacts for x64
      uses: actions/upload-artifact@v4.3.1
      with:
          name: netbakerysetup.latest
          path: .\installer\netbakerysetup.latest.exe

    - name: SFTP Upload
      # You may pin to the exact commit or the version.
      # uses: Dylan700/sftp-upload-action@50ed7273493353a60dace713957c36b02dd87bec
      uses: Dylan700/sftp-upload-action@v1.2.3
      with:
        # The SFTP server (e.g. sftp.server.com).
        server: ${{secrets.FTP_HOST2}}
        # The SFTP username.
        username: ${{secrets.FTP_USER2}}
        # The SFTP password.
        password: ${{secrets.FTP_PASS2}}
        # A list of folders to upload in the format of `folder/ => upload_folder/`
        uploads: ./installer/ => /
